### ISSUE TITLE
Is your service limited capped ?

### ISSUE THREAD

**Issue by StarDE** [JackhammerYT/RedDownloader#32]
First of all this is a very good project you should be very proud, you even used moviepy to assist in stitching audio and video together (better to use what works )! 10 Stars from me. It seems your project is only limited buy your server plan that is a pity but its understandable.

--ignore the below as I understand your limitations---

It all worked at first now it just doesn't , first it was fast then it was super slow now its just showing errors.
I personally get this error (as I tried to go back to my original working code):

`Error: Could Not Recoganize Post Type`

also got these errors as I progressed (before I realized it was broken):

#22 

there is an issue with your service as it doesn't allow one user to use it continuously  (i assume you capped how much a user can use your service).

This would mean that this is more a showcase not an actual full service ? I could be wrong.

**Comment by JackhammerYT** [comment]
Greetings

Looks like the issue you are facing is not directly related to #22 its a mix of it

RedDownloader is totally open sourced (except web server due to security reasons and is in process of being released as well), RedDownloader doesn't offer any premium plans  and I just wrote a brief about it not being able to handle a large number of requests from multiple people at the same time. that can be read at #26 

Referencing your unedited issue:
 
It appears to me that you wanted to download post from the url : `https://www.reddit.com/r/videos/comments/`?

trying to download from urls like that would yield that error as it is not a valid url and hence can't recognize the error you need to provide a direct url to the post you would like to download 

for example:
`https://www.reddit.com/r/wallpaper/comments/z7q8tr/38402160_thousand_sunny_one_piece/`
